
"""

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

"""


import numpy as np

def diff(s: str, t: str):
    sorted_s = "".join(sorted(s))
    sorted_t = sorted(t)
    for index, letters in enumerate(sorted_t):
        if sorted_s[index:].find(letters) == -1:
            return letters



print(diff("a","aa"))
print(diff(s = "abcd", t = "abcde"))




####################################################################
"""


def diff(s: str, t: str):

    list1 = []
    for letter in t:
        if letter in s and letter not in list1:
            list1.append(letter)
        else:
            return letter

print(diff("a","aa"))
print(diff(s = "abcd", t = "abcde"))




####################################################################


import numpy as np

def diff(s: str, t: str):
    s_array = np.array([x for x in s])
    t_array = np.array([y for y in t])
    return "".join(np.setdiff1d(t_array, s_array))


print(diff(s = "abcd", t = "abcde"))


"""